// This file is automatically generated. Do not edit it directly.
// NOTE: localStorage + persistSession guarded for SSR/SSG compatibility.
// If this file is regenerated by Lovable and loses these guards, the
// vite-react-ssg build will crash with 'localStorage is not defined'.
// Re-apply the `typeof window !== 'undefined'` guards if that happens.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== 'undefined';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: isBrowser ? window.localStorage : undefined,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});